-- MySQL Script generated by MySQL Workbench
-- Thu Oct 17 16:06:23 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Course` (
  `Number` INT NOT NULL,
  `Title` VARCHAR(45) NULL,
  `Credits` INT NULL,
  `Syllabus` VARCHAR(45) NULL,
  `Prerequisites` VARCHAR(45) NULL,
  PRIMARY KEY (`Number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Course Offering`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Course Offering` (
  `Section Number` INT NULL,
  `Number` INT NULL,
  `Year` INT NULL,
  `Semester` INT NULL,
  `Instructor` VARCHAR(45) NULL,
  `Timing` VARCHAR(45) NULL,
  `Classroom` INT NULL,
  INDEX `Number_idx` (`Number` ASC) VISIBLE,
  CONSTRAINT `Number`
    FOREIGN KEY (`Number`)
    REFERENCES `mydb`.`Course` (`Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Student` (
  `Student ID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Program` VARCHAR(45) NULL,
  `Course_Number` INT NOT NULL,
  PRIMARY KEY (`Student ID`, `Course_Number`),
  INDEX `fk_Student_Course1_idx` (`Course_Number` ASC) VISIBLE,
  CONSTRAINT `fk_Student_Course1`
    FOREIGN KEY (`Course_Number`)
    REFERENCES `mydb`.`Course` (`Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Instructor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Instructor` (
  `Instructor ID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Department` VARCHAR(45) NULL,
  `` VARCHAR(45) NULL,
  `Course_Number` INT NOT NULL,
  PRIMARY KEY (`Instructor ID`, `Course_Number`),
  INDEX `fk_Instructor_Course1_idx` (`Course_Number` ASC) VISIBLE,
  CONSTRAINT `fk_Instructor_Course1`
    FOREIGN KEY (`Course_Number`)
    REFERENCES `mydb`.`Course` (`Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Enrollment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Enrollment` (
  `Student ID` INT NULL,
  `Grade` VARCHAR(45) NULL,
  `Course Offering` VARCHAR(45) NULL,
  `Student_Student ID` INT NOT NULL,
  `Number` INT NULL,
  `Course_Number` INT NOT NULL,
  INDEX `Student ID_idx` (`Student ID` ASC) VISIBLE,
  PRIMARY KEY (`Student_Student ID`, `Course_Number`),
  INDEX `fk_Enrollment_Course1_idx` (`Course_Number` ASC) VISIBLE,
  CONSTRAINT `Student ID`
    FOREIGN KEY (`Student ID`)
    REFERENCES `mydb`.`Student` (`Student ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Enrollment_Student1`
    FOREIGN KEY (`Student_Student ID`)
    REFERENCES `mydb`.`Student` (`Student ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Enrollment_Course1`
    FOREIGN KEY (`Course_Number`)
    REFERENCES `mydb`.`Course` (`Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
